services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5431"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - apinetwork

  redis:
    image: redis:6.2
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - apinetwork

volumes:
  postgresdata:
    driver: local

networks:
  apinetwork:
    driver: bridge