spring:
  application:
    name: bank
  config:
    import: optional:file:.env[.properties]
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: com.elyashevich.bank.config.JacksonJsonFormatMapperCustom
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_URL:postgres}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
application:
  security:
    jwt:
      secret: ${SECRET}
      lifetime:
        access: 1800000 #30min
        refresh: 864000000 #10d
